---
title: "04.03.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting Notes: 04.03.2024 - HPC and Datasets

### What was done?

- Completed the structure of the Exploratory Data Analysis (EDA) in a Jupyter notebook to further use when we have the final dataset.
- Contacted Lottie to get help with the HPC cluster, specifically, the permission to access the purrlab_students data folder since right now we only have access to purrlab.
- Got an understanding of how to use SSH for remote access, getting more familiar with the HPC's structure.

### What we learned?

- There are several options for chest x-ray datasets, including NIH ChestXray14, CheXpert, and PadChest, giving us different choices to consider for our project.
- Determined that the NIH ChestXray14 dataset might be the best for us, given that we already have access, which would help up speed up the process.
- Learned that each dataset is either presented through a published paper or information made available on a website. This the the best way of analyzing which dataset we should focus on given the context of our project.
- Data handling libraries such as Keras or PyTorch can automate the process of loading our data from CSV files that have the image names.
- It is very important to avoid mixing x-ray images from the same patient across training and testing sets to maintain the integrity of our model’s evaluation process.

### What to do next?

- Make a final decision on the specific x-ray dataset to use for our project, considering the advantages of each:
    - NIH ChestXray14: https://www.nih.gov/news-events/news-releases/nih-clinical-center-provides-one-largest-publicly-available-chest-x-ray-datasets-scientific-community
    - CheXpert: https://stanfordmlgroup.github.io/competitions/chexpert/
    - PadChest: https://bimcv.cipf.es/bimcv-projects/padchest/
- Develop a data loader for the chosen dataset.
- Get more familiar with the ShorT framework, aiming to learn the capabilities that would allign with our methodology and research outcomes.