---
title: "05.04.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting Notes: 05.04.2024 - Meeting with Amelia

### NOTES:

- We should check if we are actually using the GPU since our code is running slow (at least slower than Amelia would expect)
- For the experiments:
    - We should start with seed 0, run the experiments, and then add more seeds incrementally according to how much time we have
    - The count of pneumothorax in the dataset is also something to consider
    - For the balanced subset of the data, its okay to have less than 30k if there isn’t that many examples to pool from
    - For the random subset, we should still check the distribution of the data, not just make it completely random
    - The plan for sex: random 40/60, balanced 50/50, imbalanced 20/80
- We can use three subsets for sex, but for drains maybe we could keep just one
    - We should do random sampling to preserve the distribution of the dataset
    - But, since we don’t have that information (no annotations for the chest drains), we have to do it randomly
- Idea for an extra experiment: check how does the size of the dataset influence the algorithms performance