---
title: "08.03.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting Notes: 08.03.2024 - EDA and multi-head classification

### What was done?

- Reviewed the research paper that introduces the Chexpert dataset and explains how the annotations were obtained, to better understand its structure and methodology.
- Modified the Exploratory Data Analysis (EDA) notebook to adjust it specifically to the Chexpert dataset, incorporating some additional analyses.
- Added text sections to the EDA notebook outlining the structure of the dataset to provide details on how the annotations were made.
- Exporing how multihead models work and how they can be coded by adding an additional output layer to the network.
- Focused on the Jupyter notebook provided by the researchers behind the ShorT paper, trying to understnd the structure of the approach and methodology they introduced.

### What we learned?

- The Chexpert dataset structure, noting that the data is somewhat balanced but also that we need to address the categorization of variables such as 'Sex' due to the presence of 'Unknown' and NaN values, the age distribution is skewed towards older patients, we need to think of handling of missing data.
- Understood the architecture and purpose of multihead prediction models, which are designed to perform both a primary classification task and an auxiliary classification simultaneously.
- Understood the way backpropagation works within multi-head models, which is crucial for training these models effectively by updating weights based on error gradients.

### What to do next?

- Address the issue related to missing images in the Chexpert dataset. Reaching out to Amelia to see whether the dataset has been uploaded correctly.
- Proceed with the coding implementation of a multi-head model, translating the theory to code, ensuring that the model can handle the complexity of an image dataset.