---
title: "13.02.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Meeting Notes: 13.02.2024 - Data Preparation

### What Was Done:

- **Finalized the Dataset Choice**: After reviewing potential datasets, we decided to proceed with the CheXpert dataset for our project, valuing its comprehensive nature and relevance to our goals.
- **Encountered Downloading Issues**: Attempted to download the CheXpert dataset but faced challenges due to its large size (471 GB), preventing us from securing the data for our project.

### What We Learned:

- **Overview of Potential Datasets**:
    - Explored various sources for medical imaging datasets, such as Papers with Code and the Stanford AIMI repository, comparing options before settling on CheXpert.
    - **CheXpert Details**:
        - Found through the Stanford ML Group and available for download via the Stanford AIMI website.
        - Includes extensive documentation and a GitHub repository for test set labels, highlighting its well-supported nature.
        - Comprises images labeled across 14 different categories, offering a broad spectrum for analysis and model training.

- **Project Outline Update**:
    - **Current Plan**: Short-circuit testing (ShorT) to identify presence of shortcuts, followed by CycleGAN for image modification, culminating in the development of a final classifier aimed at ensuring model fairness.
    - **Objective**: To detect and mitigate shortcut learning within the dataset, thereby enhancing the fairness and accuracy of our model.

### What to Do Next:

- **Address Dataset Acquisition Challenges**:
    - Prepare a set of questions for Amelia regarding the best approach to handle the CheXpert dataset's large size:
        1. **Subset Consideration**: Discuss the feasibility and implications of working with a smaller subset of the CheXpert dataset to manage size constraints.
        2. **Infrastructure Options**: Explore the possibility of using Microsoft Azure for data storage and processing, including clarifying financial responsibilities (personal vs. ITU funding).
        3. **ITU Resources**: Investigate if there are available resources at ITU, such as dedicated computers for data-intensive projects, that we could utilize to circumvent the downloading issue.

- **Next Steps Planning**:
    - **Immediate Action**: Schedule a meeting with Amelia to discuss the outlined questions and decide on the most viable path forward for dataset acquisition.
    - **Project Timeline Revision**: Depending on the outcome of the discussion with Amelia, revise the project timeline to accommodate any changes in dataset preparation and initial analysis phases.
