---
title: "19.02.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Meeting Notes: 19.02.2024 - CheXpert and ShorT

### What Was Done:

- Reviewd the paper **"Fast Diffusion-Based Counterfactuals for Shortcut Removal and Generation"**, finding its relevance to our project's objectives.
- Dedicated time to understanding **ShorT**, considering its application for detecting and addressing shortcut learning in our model.
- Initiated the creation of a GitHub repository to facilitate collaborative development and version control for our project's codebase.

### What We Learned:

- **Insights from the paper**:
    - The methodology seens like a good approach for detecting shortcuts in datasets
    - It aligns with our planned methodology for shortcut detection and mitigation.
- **Contrastive Unpaired Translation (CUT)**:
    - Innovative technique for image translation
    - Implementation to our project ([taesungp/contrastive-unpaired-translation](https://github.com/taesungp/contrastive-unpaired-translation)).

### What to Do Next:

- Solve technical issues that came up regarding data processing. 
- Understand "data flipping" in the context of TensorFlow datasets:
    - What role does flipping data play in our dataset processing, and how does it impact model training and evaluation?
    - Our TensorFlow dataset setup involves not only the original images but also a flipped version.
    