---
title: "26.03.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting Notes: 26.03.2024 - Meeting with Amelia

### NOTES:

- Remove the unknown and nan cases and check the distribution of the data
- Use regression for age and follow the ShorT paper
- Check the webinar Amelia sent with the ShorT presentation, re-read the paper and decide if we want the main task accuracy or the minimal total loss
- Dense net works the best with chest X-rays. there is a reference in Amelia’s paper to another paper that compares different approaches and concludes Dense net is the best
- We should test for all three: age, sex and chest drains
- Cross-validation is good in general for machine learning, we should use it now
- We should use 3 different seeds
- We should get the result from the baseline only detecting pneumothorax and then check the performance
- From the model, we should save the predictions, but more importantly, save the probabilities since they are the most useful later on, when dealing with performance matrices
- For the experiments, we should prioritize:
    1. baseline - performance and fairness metrics
    2. cross-validation
    3. seeds
- We shouldn’t push large files to GitHub


### What to do next?

- For us:
    - modify code to predict age
    - handle sex values
    
- For the next meeting:
    - Run experiments : Baseline and the cross-validation
    - Run experiments : Different seeds
    - Start paper: Data, introduction, related work, methods