---
title: "26.02.2024,"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Meeting Notes: 26.02.2024 - Technical setup and access to data

### What Was Done:

- Uploaded all previous meeting notes, converted into R Markdown format, to our project's GitHub repository to ensure our documentation is organized and accessible.
- Established connections to hpc cluster resources and ITU's VPN using FortiClient.
- Configuring VSCode to import the CheXpert data from the hpc to our notebook for ShorT, but ran into errors.
- Identifying and selecting a subset of the CheXpert dataset to use temporarily for initial testing and analysis.
- HPC User Group channel on teams or office hours for the HPC Tues 9am-11am at the dasya lab (5a56).

### What We Learned:

- Our VSCode environment:
    - Remote exlorer is now configured with a remote SSH connection to the hpc.
    - The GitHub repository has been cloned to our desktop on the hpc.
    - This cloned repository is opened in VSCode, syncing our code and the remote data.
- We encountered a problem with accessing the images in the dataset, receiving a "permission denied" error when accessing hpc images in our notebook.

### What to Do Next:

- Look into the hpc structure and permissions to understand the root cause of the access issue.
- Mail hpc support teams to get help.
- Join the meeting tomorrow for HPC User Group