---
title: "27.02.2024."
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Meeting Notes: 27.02.2024 - Data and EDA

### What Was Done:

- Connected to the purrlab data folder, on the hpc cluster.
- Compiled the first draft of the EDA, solid based to builld upon further.

### What We Learned:

- **Data access**:
    - Currently lack access to `purrlab_students`; an email has been sent to Lottie to resolve this.
    - The data structure is more complex than we thought, so a better understanding is needed for effective analysis.
    - There is skewness in the age distribution towards older patients, which could influence our analysis.
    - Different software versions (e.g., Python) between our setup and Amelia's code.
- **EDA plan**:
    - **1. The shape of the data:**
        - **Size**:  number of observations and features.
        - **Type of data**:  numerical, categorical, and text data.
        - **Missing Values**: detect and decide how to handle missing data.
    - **2. Summarize the data:**
        - Calculate mean, median, mode, standard deviation, quartiles, min/max values for numerical data.
        - Understand the distribution of your data, including skewness and kurtosis, plotting histograms or density plots.
    - **3. Variables individually:**
        - **Numerical variables:** histograms, box plots, or density plots to understand distributions.
        - **Categorical variables:** bar charts or pie charts to see the frequency of categories.
    - **4. Relationships between variables:**
        - Correlation matrices and scatter plots to explore potential relationships between numerical variables.
        - Analyze the relationship between categorical variables.
        - Look at your data by grouping based on certain categories or conditions.
    - **5.  Patterns or anomalies:**
        - Look for outliers, unusual observations, or patterns in your data through plots and statistical summaries.
        - Investigate any anomalies to understand their cause — they could be data entry errors, exceptional cases, or important discoveries.
    - **6. Visualize the Data**
    - **7. Test Hypotheses**
    
### What to Do Next:

- Questions:
    - A walkthrough of the data structure to understand the organization of the foolders and files.
    - Clarification on the coding for the `sex` variable (interpretation of `0` and `NaN` values).
    - The skewed age distribution, and the pedriatic entries belogning in the 60-69 and 20-29 age ranges.
- Test Principal Component Analysis (PCA) using a select few variables (study date, patient age, patient sex, labels) to identify patterns or reduce dimensionality.
- Finish the exploratory data analysis, adding any new insights or adjustments, and start coding ShorT.